### ISSUE TITLE
"Donate section" is not responsive 

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [sbk2k1/gptnews#3]
![Screenshot_2023-08-10-15-10-36-914_com.android.chrome.jpg](https://github.com/sbk2k1/gptnews/assets/69814563/074ae41b-fc5a-4621-b777-d54c8ec40b55)

**Comment by sbk2k1** [comment]
Thanks for pointing this out! Sorry, for noticing it a bit late. Will fix it later on. You can too if you want!

**Comment by BamaCharanChhandogi** [comment]
yeah! assign me, I can Contribute

**Comment by sbk2k1** [comment]
Sure!

**Comment by BamaCharanChhandogi** [comment]
Hey! Can you tell me the processes for running your project? I tried a lot but I can't.

**Comment by BamaCharanChhandogi** [comment]
#4

**Comment by sbk2k1** [comment]
Resolved!

**Comment by sbk2k1** [comment]
hey @BamaCharanChhandogi your changes break the rest of the website in other resolutions.

![image](https://github.com/sbk2k1/gptnews/assets/78817344/4273eba4-9a30-47de-aecf-ca92944e0d04)

**Comment by BamaCharanChhandogi** [comment]
don't worry. previously I didn't check for a laptop, It was my mistake. I have raised another PR. 100% correct.
review it.

**Comment by sbk2k1** [comment]
Could you please attach a video/gif of the resolutions?

**Comment by sbk2k1** [comment]
Merged!

**Comment by sbk2k1** [comment]
Merged!
